### ISSUE TITLE
Compact the installation instructions into little scripts

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/Wonoly-V2#12]
# Summary

There seems to be a lot to do for installation so I was wondering if you wanted to make a ``` .sh ``` and ``` .bat ``` script that does it for people automatically?

**Comment by mauro-balades** [comment]
Alr

**Comment by mauro-balades** [comment]
https://github.com/WillTheDeveloper/Wonoly-V2/commit/f32732cde1e8dfb8b13dfffd0b71f5eff107cdf4

**Comment by WillTheDeveloper** [comment]
Coolio
